services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
 
  - type: web
    name: my-frontend
    env: static
    plan: free
    staticPublishPath: frontend/build
    buildCommand: cd frontend && npm install && npm run build